### ISSUE TITLE
Add the option to specify a different output directory

### ISSUE THREAD

**Issue by axipher** [EpicUnknown/anime-dl_re-write#2]
First off thanks for the work on this fork.  Would you be able to add an option to specify a different output directory, even through a settings file stored in the same directory, or specified through running the command that can contain all the other command line options?

I would like to be able to download and ffmpeg on my SSD, but then have an 8 TB external hard drive hooked up as the Output folder that can easily be moved to my NAS or take with me on a trip.

**Comment by iiEpic** [comment]
That has already been created. It is the argument "-o" 

Let me know if you run into any problems! (:

**Comment by axipher** [comment]
Missed that, thanks.

Will give it a try tomorrow night when I finish setting up me new VM box.
