### ISSUE TITLE
Failing to login - potential CRFSCRAPE change required?

### ISSUE THREAD

**Issue by axipher** [EpicUnknown/anime-dl_re-write#5]
Hey Epic,

I hope you are keeping safe and healthy.

The last EXE build you provided over on the main anime-dl project stopped working today with the following error in the generated "Error Log.log"
```
DEBUG: You have successfully set the Debugging On.
DEBUG: Arguments Provided : Namespace(input=['https://www.crunchyroll.com/room-camp'], language='Japanese', password=['redacted'], range='All', resolution=['1080p'], skip=False, username=['redacted'], verbose=True, version=False)
DEBUG: Operating System : Windows - 10 - 10.0.17763
DEBUG: Python Version : 2.7.15 (64bit)
DEBUG: crunchy_login_url : https://www.crunchyroll.com/login
DEBUG: Starting new HTTPS connection (1): www.crunchyroll.com:443
DEBUG: https://www.crunchyroll.com:443 "GET /login HTTP/1.1" 503 None
ERROR: Error executing Cloudflare IUAM Javascript. Cloudflare may have changed their technique, or there may be a bug in the script.

Please read https://github.com/Anorov/cloudflare-scrape#updates, then file a bug report at https://github.com/Anorov/cloudflare-scrape/issues."
```

The current code on here also stopped working today with the following error in the generated "Error Log.log":
```
DEBUG: You have successfully set the Debugging On.
DEBUG: Arguments Provided : Namespace(input=['https://www.crunchyroll.com/room-camp'], language='Japanese', nologin=False, output=None, password=['redacted'], range='All', resolution=['1080p'], skip=False, username=['redacted'], verbose=True, version=False)
DEBUG: Operating System : Windows - 10 - 10.0.17763
DEBUG: Python Version : 3.7.4 (32bit)
DEBUG: Starting new HTTPS connection (1): www.crunchyroll.com:443
DEBUG: https://www.crunchyroll.com:443 "GET /login HTTP/1.1" 503 None
DEBUG: Resetting dropped connection: www.crunchyroll.com
DEBUG: https://www.crunchyroll.com:443 "GET /cdn-cgi/l/chk_jschl?jschl_vc=redacted&pass=redacted&jschl_answer=redacted HTTP/1.1" 503 None
```

Those last two lines just repeat indefinitely until I hit CTRL+C in my PowerShell instance and it had 31 attempts to reset the connection at that point with no verbose output.

**Comment by iiEpic** [comment]
So I just made this exe attached and tested it this morning. (April 7th @ 0744) I had no problems with it downloading Room Camp episodes 1 and 2. Please let me know if it fixes your problem, if it does I'll upload it as an official file download.

[__main__.zip](https://github.com/EpicUnknown/anime-dl_re-write/files/4443944/__main__.zip)

**Comment by axipher** [comment]
So I tried your new __main__.exe and it was working (April 7th @ 0801 EDT) so I tried the latest code form here and that was also back to logging in correctly as well.

But for some reason it won't grab 1080p of Room Camp and I already have 1080p versions of Episode 1 through 11.  So it could be something on Crunchyroll's end.  I normally have the "-r 1080p" flag added but had to remove that for it to jump down to 720p quality from the m3u8 file.

**Comment by iiEpic** [comment]
Ah I can't really check the 1080p quality because my subscription is expired however let me know if anything changes and it randomly lets you get 1080 again!

**Comment by axipher** [comment]
Sure thing, I'll try again this afternoon to see if it's started playing nicely again.

**Comment by axipher** [comment]
Ran a test on "Room Camp" and it seems to be playing nicely again, must have been a CR issue.

Let me know if you need help testing it, closing for now.
